spring:
  jpa:
    open-in-view: false
  profiles:
    active: ${ENVIRONMENT}
  web:
    resources:
      add-mappings: false
  application:
    name: devsu-test-cuenta
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
