CREATE TABLE IF NOT EXISTS cuenta (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    tipoCuenta INTEGER NOT NULL,
    numeroCuenta DECIMAL NOT NULL,
    saldoInicial DECIMAL NOT NULL,
    saldoDisponible DECIMAL NOT NULL,
    estado BOOLEAN NOT NULL,
    cliente VARCHAR(100) NOT NULL

);

CREATE TABLE IF NOT EXISTS movimiento (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    fecha TIMESTAMP NOT NULL,
    tipoMovimiento VARCHAR(100) NOT NULL,
    valor DECIMAL NOT NULL,
    saldo DECIMAL NOT NULL,
    numeroCuenta INTEGER NOT NULL,
    FOREIGN KEY (numeroCuenta) REFERENCES cuenta(numeroCuenta)

);