CREATE TABLE IF NOT EXISTS cuenta (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    tipoCuenta INTEGER NOT NULL,
    numeroCuenta DECIMAL NOT NULL,
    saldoInicial DECIMAL NOT NULL,
    estado BOOLEAN NOT NULL,

);

CREATE TABLE IF NOT EXISTS movimiento (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    fecha TIMESTAMP NOT NULL,
    tipoMovimiento DECIMAL NOT NULL,
    valor DECIMAL NOT NULL,
    saldo DECIMAL NOT NULL,
    cuentaId INTEGER NOT NULL,
    FOREIGN KEY (cuentaId) REFERENCES cuenta(id)

);